language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - pip install coveralls --use-mirrors
script:
  - nosetests --with-coverage --cover-package=application_only_auth
after_success:
  - coveralls
